#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# accepts four parameters:
# $1 - the path to file to be transferred
# $2 - the IP of the server
# $3 - username scp connects with
# $4 - path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
