#!/usr/bin/env bash
# Bash script to redirect nginx server to another
#+ page
# Redirection is "301 Moved Permanently"
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://bruka.tech/;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
