#!/usr/bin/env bash
# This script displays a clock for hours and minutes
# up to 12 hours and 59 minutes

HOUR=0
MINUTE=1
while [ $HOUR -le 12 ]; do
    echo "Hour: ${HOUR}"
    while [ $MINUTE -lt 60 ]; do
	echo $MINUTE
	(( MINUTE+=1))
    done
    (( MINUTE=0))
    (( HOUR+=1))
done
